<p style="text-align: right; font-size: small;">
Learning materials by Tamsin Huggins
</p>

# Titanic Data Wrangling Solutions


### a) Use Pandas to load the Titanic dataset.

In [1]:
import pandas as pd
df = pd.read_csv('../data/titanic.csv')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
2,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
3,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
4,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
178,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
179,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
180,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
181,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

### b) Perform data exploration on the Titanic data.

Your exploration could investigate the following:
- What do the first 5 rows of the data look like?
- What are column names?
- What are the datatypes of each column?

Your code in the cell(s) below:

In [2]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
2,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
3,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
4,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

In [3]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [4]:
df.dtypes

survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

### c) Select the 'fare' column from the titanic DataFrame

your code in the cell(s) below:

In [5]:
df['fare']

0      71.2833
1      53.1000
2      51.8625
3      16.7000
4      26.5500
        ...
177    52.5542
178     5.0000
179    83.1583
180    30.0000
181    30.0000
Name: fare, Length: 182, dtype: float64

### d) Investigate the fares that passengers payed to travel on the Titanic.

- What is the highest fare anyone payed to ride the titanic?
- what is the average fare payed by titanic passengers?
- How many passengers boarded the titanic for free?

Your code in the cell(s) below:

In [6]:
df['fare'].max()

512.3292

In [7]:
df['fare'].mean()

78.91973516483515

In [8]:
df[df['fare'] == 0].shape[0]

2

### e) What are the distinct values held in the 'class' column?

In other words, what are the cateogory names held in this column?

Your code in the cell(s) below:

In [9]:
df['class'].unique()

array(['First', 'Third', 'Second'], dtype=object)

### f) Create a new column which holds the date of birth of each passenger. Call this new column 'D.O.B'

 - Assume that the 'age' column in the data represents passengers' ages when the titanic set sail, in **1912**.
 
 Your code in the cell(s) below:

In [10]:
df['D.O.B'] = 1912 - df['age']
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,D.O.B
0,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1874.0
1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1877.0
2,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,1858.0
3,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,1908.0
4,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,1854.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,1865.0
178,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,1879.0
179,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,1856.0
180,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1893.0
181,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1886.0

In [11]:
df['D.O.B'] = df['D.O.B'].astype(int)  # convert from float to int

In [12]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,D.O.B
0,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1874
1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1877
2,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,1858
3,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,1908
4,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,1854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,1865
178,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,1879
179,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,1856
180,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1893
181,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1886