<p style="text-align: right; font-size: small;">
Learning materials by Tamsin Huggins
</p>

# Challenge 1: Winter Olympics

1) Import the Pandas package as pd

In [2]:
import pandas as pd

2) Read in the data and save it to a variable called df. The data is held in a CSV file called winter in the Data folder.

In [3]:
df = pd.read_csv('../data/winter.csv')
df

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1924,Chamonix,Biathlon,Biathlon,"BERTHET, G.",FRA,Men,Military Patrol,Bronze
1,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, C.",FRA,Men,Military Patrol,Bronze
2,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, Maurice",FRA,Men,Military Patrol,Bronze
3,1924,Chamonix,Biathlon,Biathlon,"VANDELLE, André",FRA,Men,Military Patrol,Bronze
4,1924,Chamonix,Biathlon,Biathlon,"AUFDENBLATTEN, Adolf",SUI,Men,Military Patrol,Gold
...,...,...,...,...,...,...,...,...,...
5765,2014,Sochi,Skiing,Snowboard,"JONES, Jenny",GBR,Women,Slopestyle,Bronze
5766,2014,Sochi,Skiing,Snowboard,"ANDERSON, Jamie",USA,Women,Slopestyle,Gold
5767,2014,Sochi,Skiing,Snowboard,"MALTAIS, Dominique",CAN,Women,Snowboard Cross,Silver
5768,2014,Sochi,Skiing,Snowboard,"SAMKOVA, Eva",CZE,Women,Snowboard Cross,Gold
5769,2014,Sochi,Skiing,Snowboard,"TRESPEUCH, Chloe",FRA,Women,Snowboard Cross,Bronze

3) Display just the first 5 rows of the data

In [3]:
df.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1924,Chamonix,Biathlon,Biathlon,"BERTHET, G.",FRA,Men,Military Patrol,Bronze
1,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, C.",FRA,Men,Military Patrol,Bronze
2,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, Maurice",FRA,Men,Military Patrol,Bronze
3,1924,Chamonix,Biathlon,Biathlon,"VANDELLE, André",FRA,Men,Military Patrol,Bronze
4,1924,Chamonix,Biathlon,Biathlon,"AUFDENBLATTEN, Adolf",SUI,Men,Military Patrol,Gold

4) Display just the last 5 rows of the data.

In [4]:
df.tail()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
5765,2014,Sochi,Skiing,Snowboard,"JONES, Jenny",GBR,Women,Slopestyle,Bronze
5766,2014,Sochi,Skiing,Snowboard,"ANDERSON, Jamie",USA,Women,Slopestyle,Gold
5767,2014,Sochi,Skiing,Snowboard,"MALTAIS, Dominique",CAN,Women,Snowboard Cross,Silver
5768,2014,Sochi,Skiing,Snowboard,"SAMKOVA, Eva",CZE,Women,Snowboard Cross,Gold
5769,2014,Sochi,Skiing,Snowboard,"TRESPEUCH, Chloe",FRA,Women,Snowboard Cross,Bronze

5) Display just the first 3 rows of the data.

In [5]:
df.head(3)

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1924,Chamonix,Biathlon,Biathlon,"BERTHET, G.",FRA,Men,Military Patrol,Bronze
1,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, C.",FRA,Men,Military Patrol,Bronze
2,1924,Chamonix,Biathlon,Biathlon,"MANDRILLON, Maurice",FRA,Men,Military Patrol,Bronze

6) Use the columns attribute of the DataFrame to give a list of the column names.

In [6]:
df.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete', 'Country', 'Gender',
       'Event', 'Medal'],
      dtype='object')

7) Display the number of rows and columns in the DataFrame.

In [7]:
df.shape

(5770, 9)

8) Select just the Athlete column.

In [8]:
df['Athlete']

0                BERTHET, G.
1             MANDRILLON, C.
2        MANDRILLON, Maurice
3            VANDELLE, André
4       AUFDENBLATTEN, Adolf
                ...
5765            JONES, Jenny
5766         ANDERSON, Jamie
5767      MALTAIS, Dominique
5768            SAMKOVA, Eva
5769        TRESPEUCH, Chloe
Name: Athlete, Length: 5770, dtype: object

9) Select the columns Sport and Discipline so that they display side-by-side

In [9]:
df[['Sport', 'Discipline']]

         Sport Discipline
0     Biathlon   Biathlon
1     Biathlon   Biathlon
2     Biathlon   Biathlon
3     Biathlon   Biathlon
4     Biathlon   Biathlon
...        ...        ...
5765    Skiing  Snowboard
5766    Skiing  Snowboard
5767    Skiing  Snowboard
5768    Skiing  Snowboard
5769    Skiing  Snowboard

[5770 rows x 2 columns]

10) What are the data types of all the columns in the DataFrame?

In [10]:
df.dtypes

Year           int64
City          object
Sport         object
Discipline    object
Athlete       object
Country       object
Gender        object
Event         object
Medal         object
dtype: object

11) a) Display just the unique values in the Medal columns

In [11]:
df['Medal'].unique()

array(['Bronze', 'Gold', 'Silver'], dtype=object)

11) b) Use the .shape attribute to count the number of unique values held in the Medal column

In [12]:
df['Medal'].unique().shape

(3,)

12) How many unique disciplines are there in the Discipline column?

In [13]:
df['Discipline'].unique().shape

(15,)

13) Calculate how many years there were between the first Winter Olympics in the data and the most recent Winter Olmpics in the data.

In [14]:
df['Year'].max() - df['Year'].min()

90

14) a) Select just the data where the discipline is snowboarding (Snowboard).

In [15]:
df[df['Discipline'] == 'Snowboard']

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
3605,1998,Nagano,Skiing,Snowboard,"KESTENHOLZ, Ueli",SUI,Men,Giant-Slalom,Bronze
3606,1998,Nagano,Skiing,Snowboard,"REBAGLIATI, Ross",CAN,Men,Giant-Slalom,Gold
3607,1998,Nagano,Skiing,Snowboard,"PRUGGER, Thomas",ITA,Men,Giant-Slalom,Silver
3608,1998,Nagano,Skiing,Snowboard,"KOECK, Brigitte",AUT,Women,Giant-Slalom,Bronze
3609,1998,Nagano,Skiing,Snowboard,"RUBY, Karine",FRA,Women,Giant-Slalom,Gold
...,...,...,...,...,...,...,...,...,...
5765,2014,Sochi,Skiing,Snowboard,"JONES, Jenny",GBR,Women,Slopestyle,Bronze
5766,2014,Sochi,Skiing,Snowboard,"ANDERSON, Jamie",USA,Women,Slopestyle,Gold
5767,2014,Sochi,Skiing,Snowboard,"MALTAIS, Dominique",CAN,Women,Snowboard Cross,Silver
5768,2014,Sochi,Skiing,Snowboard,"SAMKOVA, Eva",CZE,Women,Snowboard Cross,Gold
5769,2014,Sochi,Skiing,Snowboard,"TRESPEUCH, Chloe",FRA,Women,Snowboard Cross,Bronze

14) b) Select again the data where the discipline is snowboarding. This time, save the resulting DataFrame to a new variable called snowboard_df.

In [16]:
snowboard_df = df[df['Discipline'] == 'Snowboard']

14) c) Using your snowboard_df DataFrame, select the data where 'Medal' is equal to 'Gold'

In [17]:
snowboard_df[snowboard_df['Medal'] == 'Gold']

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
3606,1998,Nagano,Skiing,Snowboard,"REBAGLIATI, Ross",CAN,Men,Giant-Slalom,Gold
3609,1998,Nagano,Skiing,Snowboard,"RUBY, Karine",FRA,Women,Giant-Slalom,Gold
3612,1998,Nagano,Skiing,Snowboard,"SIMMEN, Gian",SUI,Men,Half-Pipe,Gold
3615,1998,Nagano,Skiing,Snowboard,"THOST, Nicola",GER,Women,Half-Pipe,Gold
4087,2002,Salt Lake City,Skiing,Snowboard,"SCHOCH, Philipp",SUI,Men,Giant Parallel Slalom,Gold
4090,2002,Salt Lake City,Skiing,Snowboard,"BLANC, Isabelle",FRA,Women,Giant Parallel Slalom,Gold
4093,2002,Salt Lake City,Skiing,Snowboard,"POWERS, Ross",USA,Men,Half-Pipe,Gold
4096,2002,Salt Lake City,Skiing,Snowboard,"CLARK, Kelly",USA,Women,Half-Pipe,Gold
4612,2006,Turin,Skiing,Snowboard,"SCHOCH, Philipp",SUI,Men,Giant Parallel Slalom,Gold
4615,2006,Turin,Skiing,Snowboard,"MEULI, Daniela",SUI,Women,Giant Parallel Slalom,Gold
4618,2006,Turin,Skiing,Snowboard,"WHITE, Shaun",USA,Men,Half-Pipe,Gold
4621,2006,Turin,Skiing,Snowboard,"TETER, Hannah",USA,Women,Half-Pipe,Gold
4624,2006,Turin,Skiing,Snowboard,"WESCOTT, Seth",USA,Men,Snowboard Cross,Gold
4627,2006,Turin,Skiing,Snowboard,"FRIEDEN, Tanja",SUI,Women,Snowboard Cross,Gold
5141,2010,Vancouver,Skiing,Snowboard,"ANDERSON, Jasey Jay",CAN,Men,Giant Parallel Slalom,Gold
5144,2010,Vancouver,Skiing,Snowboard,"SAUERBREIJ, Nicolien",NED,Women,Giant Parallel Slalom,Gold
5147,2010,Vancouver,Skiing,Snowboard,"WHITE, Shaun",USA,Men,Half-Pipe,Gold
5150,2010,Vancouver,Skiing,Snowboard,"BRIGHT, Torah",AUS,Women,Half-Pipe,Gold
5153,2010,Vancouver,Skiing,Snowboard,"WESCOTT, Seth",USA,Men,Snowboard Cross,Gold
5156,2010,Vancouver,Skiing,Snowboard,"RICKER, Maelle",CAN,Women,Snowboard Cross,Gold
5740,2014,Sochi,Skiing,Snowboard,"WILD, Vic",RUS,Men,Giant Parall.S.,Gold
5745,2014,Sochi,Skiing,Snowboard,"PODLADTCHIKOV, Iouri",SUI,Men,Half-Pipe,Gold
5747,2014,Sochi,Skiing,Snowboard,"WILD, Vic",RUS,Men,Parallel Slalom,Gold
5751,2014,Sochi,Skiing,Snowboard,"KOTSENBURG, Sage",USA,Men,Slopestyle,Gold
5752,2014,Sochi,Skiing,Snowboard,"VAULTIER, Pierre",FRA,Men,Snowboard Cross,Gold
5757,2014,Sochi,Skiing,Snowboard,"KUMMER, Patrizia",SUI,Women,Giant Parall.S.,Gold
5760,2014,Sochi,Skiing,Snowboard,"FARRINGTON, Kaitlyn",USA,Women,Half-Pipe,Gold
5761,2014,Sochi,Skiing,Snowboard,"DUJMOVITS, Julia",AUT,Women,Parallel Slalom,Gold
5766,2014,Sochi,Skiing,Snowboard,"ANDERSON, Jamie",USA,Women,Slopestyle,Gold
5768,2014,Sochi,Skiing,Snowboard,"SAMKOVA, Eva",CZE,Women,Snowboard Cross,Gold

14) d) Select just the names of the athletes who won gold in the snowboarding.

In [18]:
snowboard_df[snowboard_df['Medal'] == 'Gold']['Athlete']

3606        REBAGLIATI, Ross
3609            RUBY, Karine
3612            SIMMEN, Gian
3615           THOST, Nicola
4087         SCHOCH, Philipp
4090         BLANC, Isabelle
4093            POWERS, Ross
4096            CLARK, Kelly
4612         SCHOCH, Philipp
4615          MEULI, Daniela
4618            WHITE, Shaun
4621           TETER, Hannah
4624           WESCOTT, Seth
4627          FRIEDEN, Tanja
5141     ANDERSON, Jasey Jay
5144    SAUERBREIJ, Nicolien
5147            WHITE, Shaun
5150           BRIGHT, Torah
5153           WESCOTT, Seth
5156          RICKER, Maelle
5740               WILD, Vic
5745    PODLADTCHIKOV, Iouri
5747               WILD, Vic
5751        KOTSENBURG, Sage
5752        VAULTIER, Pierre
5757        KUMMER, Patrizia
5760     FARRINGTON, Kaitlyn
5761        DUJMOVITS, Julia
5766         ANDERSON, Jamie
5768            SAMKOVA, Eva
Name: Athlete, dtype: object

14) e) Are there any snowboarders who have won gold twice? If so, how many snowboarders have done so?

In [19]:
snowboard_df[snowboard_df['Medal'] == 'Gold']['Athlete'].value_counts()

SCHOCH, Philipp         2
WHITE, Shaun            2
WESCOTT, Seth           2
WILD, Vic               2
REBAGLIATI, Ross        1
BRIGHT, Torah           1
ANDERSON, Jamie         1
DUJMOVITS, Julia        1
FARRINGTON, Kaitlyn     1
KUMMER, Patrizia        1
VAULTIER, Pierre        1
KOTSENBURG, Sage        1
PODLADTCHIKOV, Iouri    1
RICKER, Maelle          1
ANDERSON, Jasey Jay     1
SAUERBREIJ, Nicolien    1
RUBY, Karine            1
FRIEDEN, Tanja          1
TETER, Hannah           1
MEULI, Daniela          1
CLARK, Kelly            1
POWERS, Ross            1
BLANC, Isabelle         1
THOST, Nicola           1
SIMMEN, Gian            1
SAMKOVA, Eva            1
Name: Athlete, dtype: int64