
# Selecting Data with `loc` and `iloc`
---

In this notebook, we’ll focus on selecting and slicing data in pandas DataFrames using two powerful indexing methods: `loc` and `iloc`. Mastering these tools is essential for efficient data manipulation and analysis in Python.

The index in a DataFrame is a label-based reference for rows. It often serves as a unique identifier for each row, which can be leveraged with `loc` for quick access and more intuitive data manipulation.

### What You’ll Learn
- **`loc`**: Indexing by label, allowing you to select rows and columns based on names and conditions.
- **`iloc`**: Indexing by position, enabling you to select rows and columns using integer positions.
- **`set_index`**: How to set a column  to be the index.
- **DataFrame Slicing**: Practice selecting specific subsets of data.

Import pandas and load the data

In [1]:
import pandas as pd
df = pd.read_csv('../data/world_population.csv')
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,NaN,33753499.0,28189672.0,NaN,10694796.0,12486631.0,10752971,652230,63.0587,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,NaN,NaN,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,NaN,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371,266000,2.1654,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607,527968,63.8232,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671,752612,26.5976,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918,390757,41.7665,0.20
234,33,ARG,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803,2780400,16.3683,0.57

---

## `iloc`

The `iloc` indexer is used to select rows and columns in a DataFrame based on their position (i.e., by numerical index). This makes it very useful when you want to select data from a specific location in the DataFrame.

### Syntax

For selecting a row based on its position:

> df.iloc[row_index]

For selecting a piece of data based on row and column position

>df.iloc[row_index, column_index]



Note: Why Use Square Brackets?
Unlike some other DataFrame operations, iloc is not a method, so we use square brackets [] instead of round brackets () to access it. This is because iloc is an indexer, a tool for accessing specific parts of the data. Square brackets signal that we’re selecting a specific slice or subset of data, much like indexing or slicing with lists in Python.

Select the row at position 210

In [2]:
df.iloc[210]

Rank                                  197
CCA3                                  TON
Country                             Tonga
Capital                        Nuku‘alofa
Continent                         Oceania
2022 Population                  106858.0
2020 Population                  105254.0
2015 Population                  106122.0
2010 Population                  107383.0
2000 Population                  102603.0
1990 Population                   98727.0
1980 Population                   96708.0
1970 Population                     86484
Area (km²)                            747
Density (per km²)                143.0495
World Population Percentage           0.0
Name: 210, dtype: object

select the row at position 23

select the item at row 210 and column 4

In [3]:
df.iloc[210, 4]

'Oceania'

### <span style="color:green"> iloc challenge </span>

1. Select the row at position 92
2. Select the piece of data at row position 60 and column position 5

---

## Setting a New Index with `set_index`

To make the 'CCA3'column the index of the DataFrame, use the `set_index` method. This allows you to access rows directly by their 'CCA3' values instead of the default integer index.

### Why Set a Custom Index?

By setting CCA3 as the index, you enable more intuitive data selection using the loc indexer. Instead of selecting rows by integer position, you can now use loc to select rows based on the country codes in the CCA3 colu

### What can be used as an index?
Commonly, a specific column is set as the index, especially if it contains identifiers or labels that represent rows uniquely, such as IDs, dates, or categories.

### Does an index have to be unique for every row?
**Uniqueness:** An index doesn’t have to be unique, but it’s often beneficial for easier data retrieval and analysis. For example, if each row represents a unique entry (like a country code or product ID), then a unique index makes accessing specific rows with loc more predictable and reliable.

**Non-Unique Indexes:** You can have non-unique index values, which is useful in cases like grouping by categories. When using loc with a non-unique index, it will return all matching rows.

In [4]:
df.set_index('CCA3', inplace = True)
df

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,NaN,33753499.0,28189672.0,NaN,10694796.0,12486631.0,10752971,652230,63.0587,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,NaN,NaN,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,NaN,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.00
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371,266000,2.1654,0.01
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607,527968,63.8232,0.42
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671,752612,26.5976,0.25
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918,390757,41.7665,0.20
ARG,33,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803,2780400,16.3683,0.57

## Using `loc`

Use `loc` to select the row representing France (CCA3 value is FRA)

In [5]:
df.loc['FRA']

Rank                                   23
Country                            France
Capital                             Paris
Continent                          Europe
2022 Population                64626628.0
2020 Population                64480053.0
2015 Population                63809769.0
2010 Population                62444567.0
2000 Population                58665453.0
1990 Population                56412897.0
1980 Population                53713830.0
1970 Population                  50523586
Area (km²)                         551695
Density (per km²)                117.1419
World Population Percentage          0.81
Name: FRA, dtype: object

Use `loc` to select the row representing Ireland (CCA3 value is IRL)

In [6]:
df.loc['IRL']

Rank                                 125
Country                          Ireland
Capital                           Dublin
Continent                         Europe
2022 Population                5023109.0
2020 Population                4946119.0
2015 Population                4665760.0
2010 Population                4524585.0
2000 Population                3768950.0
1990 Population                3485374.0
1980 Population                3391387.0
1970 Population                  2937637
Area (km²)                         70273
Density (per km²)                71.4799
World Population Percentage         0.06
Name: IRL, dtype: object


---
## Slicing with `iloc`

Slicing with `iloc` allows you to select specific portions of your DataFrame based on numerical indices. This is extremely useful when you want to:

- **Inspect Data**: View a subset of your data to understand its structure or contents.
- **Subset Data**: Create smaller DataFrames for analysis or testing.
- **Manipulate Data**: Apply operations to specific rows or columns.

### Syntax 
> df.iloc[ start_row : end_row , start_column : end_column ]


### Notes

- **Indexing is zero-based**: The first element is at position 0.
- **The end index is exclusive**: The element at the end index is not included in the slice.

Select the first 5 rows

In [7]:
df.iloc[0:5]

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,NaN,33753499.0,28189672.0,NaN,10694796.0,12486631.0,10752971,652230,63.0587,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,NaN,NaN,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,NaN,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.00
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.00

Select the first 5 rows, with 0 assumed for start_row

In [8]:
df.iloc[:5]

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,NaN,33753499.0,28189672.0,NaN,10694796.0,12486631.0,10752971,652230,63.0587,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,NaN,NaN,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,NaN,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.00
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.00

Select rows from position 5 to 7, columns from position 6 to 9

In [9]:
df.iloc[5:8, 6:10]

      2015 Population  2010 Population  2000 Population  1990 Population
CCA3
AGO        28127721.0       23364185.0       16394062.0       11828638.0
AIA           14525.0          13172.0          11047.0           8316.0
ATG           89941.0          85695.0          75055.0          63328.0

Select all rows for columns at positions 1 to 3

In [10]:
df.iloc[:, 1:4]

             Country           Capital      Continent
CCA3
AFG      Afghanistan             Kabul           Asia
ALB          Albania            Tirana         Europe
DZA          Algeria           Algiers         Africa
ASM   American Samoa         Pago Pago        Oceania
AND          Andorra  Andorra la Vella         Europe
...              ...               ...            ...
ESH   Western Sahara          El Aaiún         Africa
YEM            Yemen             Sanaa           Asia
ZMB           Zambia            Lusaka         Africa
ZWE         Zimbabwe            Harare         Africa
ARG        Argentina      Buenos Aires  South America

[235 rows x 3 columns]