# Dealing with Missing Values

---


## Overview



**Nan Values** 
- What is a NaN value?

**Missing Data** 
- Detecting
- Removing
- Filling in

**Data Transformation**
- Imputing
- Replacing Values

Import packages

In [1]:
import pandas as pd
import numpy as np

### Import data and set index

In [2]:
df = pd.read_csv('../data/world_population_dirty.csv', index_col='CCA3')
df

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,NaN,33753499.0,28189672.0,NaN,10694796.0,12486631.0,10752971,652230,63.0587,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,NaN,NaN,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,NaN,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.00
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371,266000,2.1654,0.01
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607,527968,63.8232,0.42
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671,752612,26.5976,0.25
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918,390757,41.7665,0.20
ARG,33,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803,2780400,16.3683,0.57

---
## What is NaN?

In Python, **NaN** stands for "Not a Number." It is a special floating-point value defined in the `numpy` library to represent missing, undefined, or unrepresentable numeric data. NaN is commonly encountered in datasets when:
- A value is missing.
- A calculation results in an undefined value (e.g., `0/0` or the square root of a negative number).

NaN behaves uniquely:
- It is not equal to any other value, including itself.
- It is often used as a placeholder in numerical computations and data analysis.



NaN is:
- Not A Number
- Different from all other data types
- Not equal to anything

- Defined in `numpy`

### Comparing NaN to other values

NaN is not equal to True, False, 0 or Empty Strings

In [3]:
from numpy import NaN 

print(NaN == True)

print(NaN == False)

print(NaN == 0)

print(NaN == '')

False
False
False
False


---
## Detect missing data

Pandas includes a number of functions to detect missing or invalid data.
The `df.isna()` method is used to detect missing values (NaN) in the DataFrame. By default, it returns a DataFrame of the same shape as `df`, with `True` indicating a missing value and `False` otherwise.

In [4]:

df.isna()

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False
ALB,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
DZA,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False
ASM,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
AND,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ESH,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
YEM,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
ZMB,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
ZWE,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
ARG,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

- `.notna()` - inverse of isna

In [5]:

df.notna()

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,True,True,True,True,True,False,True,True,False,True,True,True,True,True,True
ALB,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
DZA,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True
ASM,True,True,True,True,False,True,True,True,True,True,True,True,True,True,True
AND,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ESH,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
YEM,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
ZMB,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
ZWE,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
ARG,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

---

## Chaining `isna()` with Other Functions 

`.isna()` gives us a True/False table, highlighing NaN values with `True` (which is equivalent to `1`) and `False` (which is equivalent to `0`). We can then perform functions over this table True/False DataFrame to summarise and aggregate.

#### `.any()` For identifying the locations of missing values

#### Identify **columns** with missing values

The `df.isna()` method is used to detect missing values (NaN) in the DataFrame.

In [6]:
df.isna().any()

Rank                           False
Country                        False
Capital                        False
Continent                      False
2022 Population                 True
2020 Population                 True
2015 Population                 True
2010 Population                 True
2000 Population                 True
1990 Population                 True
1980 Population                 True
1970 Population                False
Area (km²)                     False
Density (per km²)              False
World Population Percentage    False
dtype: bool

#### Identify **rows** that contain missing values

The `df.isna()` method is used to detect missing values (NaN) in the DataFrame. 

The `.any()` method is a boolean aggregation function that checks whether **at least one** value in the specified axis is `True`. 

By setting `axis=1`, we instruct Pandas to perform this aggregation across the **columns** for each row. As a result, this will return a Series of boolean values, where `True` indicates that the corresponding row contains **at least one missing value**, and `False` indicates that the row contains no missing values.

In [7]:
df.isna().any(axis=1)

CCA3
AFG     True
ALB    False
DZA     True
ASM     True
AND    False
       ...
ESH    False
YEM    False
ZMB    False
ZWE    False
ARG    False
Length: 235, dtype: bool

Show rows that contain missing values

In [8]:
df[df.isna().any(axis=1)]

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,NaN,33753499.0,28189672.0,NaN,10694796.0,12486631.0,10752971,652230,63.0587,0.52
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,NaN,NaN,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,NaN,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.00
ARM,140,Armenia,Yerevan,Asia,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,NaN,2534377,29743,93.4831,0.03
BLR,96,Belarus,Minsk,Europe,9534954.0,9633740.0,9700609.0,NaN,NaN,NaN,9817257.0,9170786,207600,45.9295,0.12
BWA,144,Botswana,Gaborone,Africa,2630296.0,2546402.0,NaN,NaN,1726985.0,1341474.0,938578.0,592244,582000,4.5194,0.03
NIU,232,Niue,Alofi,Oceania,1934.0,1942.0,1847.0,NaN,NaN,2533.0,3637.0,5185,260,7.4385,0.00
SLB,166,Solomon Islands,Honiara,Oceania,724273.0,691191.0,612660.0,540394.0,429978.0,NaN,233668.0,172833,28896,25.0648,0.01

Identify columns containing missing values

By comparning the shape of the column with its value counts we can also see if there are missing values


#### `.sum()`

- This function calculates the sum along a specified axis. By default, it sums along each column (`axis=0`).
- When applied to the boolean DataFrame returned by `.isna()`, it treats `True` as `1` and `False` as `0`.
- The result is a Series where each value represents the count of missing values in the corresponding column.

In [9]:
# How many in each column
df.isna().sum()

Rank                           0
Country                        0
Capital                        0
Continent                      0
2022 Population                1
2020 Population                1
2015 Population                2
2010 Population                4
2000 Population                3
1990 Population                2
1980 Population                1
1970 Population                0
Area (km²)                     0
Density (per km²)              0
World Population Percentage    0
dtype: int64

### Summing missing data over the rows

If you want to sum the missing values over the rows instead of the columns, you can set `axis=1` to flip the direction in which the calculation is 
performed

Here we see that AND (the row representing Andorra) has a missing value.

In [10]:
df.isna().sum(axis=1)

CCA3
AFG    2
ALB    0
DZA    2
ASM    1
AND    0
      ..
ESH    0
YEM    0
ZMB    0
ZWE    0
ARG    0
Length: 235, dtype: int64

#### Calculate total missing values over the DataFrame
`df.isna().sum().sum()`

- **Step 1: `df.isna()`**
  - This checks for missing values (NaN) in the DataFrame.
  - It returns a DataFrame of the same shape where each cell is `True` if the value is missing, otherwise `False`.

- **Step 2: `.sum()` (First Sum)**
  - This calculates the sum along each column (`axis=0`) of the boolean DataFrame returned by `.isna()`.
  - Since `True` is treated as `1` and `False` as `0`, this results in a Series where each value represents the count of missing values in the corresponding column.

- **Step 3: `.sum()` (Second Sum)**
  - This calculates the sum of the Series obtained in Step 2.
  - The result is a single number representing the total count of missing values across all columns and rows of the original DataFrame.

In [11]:
df.isna().sum().sum()

14


---
## Dealing with Missing Values

What can we do with NaNs?

 - drop (remove) rows
 - drop (remove) columns
 - fill NaNs in with hard-coded values
 - fill NaNs in with computer-caluclated values (e.g. interpolate)
 -

### Remove missing values with`.dropna()`

- **dropna()**  - Will detect and remove rows or columns (it's usually used for rows) where data is missing.

- Returns a copy, not the original.

- Catch result in a new variable OR set **inplace=True** to alter the original DataFrame.

### Drop rows with missing values

In [12]:
df.dropna()  #inplace=True

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.00
AGO,42,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700,1246700,28.5466,0.45
AIA,224,Anguilla,The Valley,North America,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283,91,174.2527,0.00
ATG,201,Antigua and Barbuda,Saint John’s,North America,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516,442,212.1335,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371,266000,2.1654,0.01
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607,527968,63.8232,0.42
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671,752612,26.5976,0.25
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918,390757,41.7665,0.20
ARG,33,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803,2780400,16.3683,0.57

### Drop columns with missing values

- You can set `axis=1` to drop columns instead of rows

In [13]:
df.dropna(axis=1) #inplace=True

,Rank,Country,Capital,Continent,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,10752971,652230,63.0587,0.52
ALB,138,Albania,Tirana,Europe,2324731,28748,98.8702,0.04
DZA,34,Algeria,Algiers,Africa,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,27075,199,222.4774,0.00
AND,203,Andorra,Andorra la Vella,Europe,19860,468,170.5641,0.00
...,...,...,...,...,...,...,...,...
ESH,172,Western Sahara,El Aaiún,Africa,76371,266000,2.1654,0.01
YEM,46,Yemen,Sanaa,Asia,6843607,527968,63.8232,0.42
ZMB,63,Zambia,Lusaka,Africa,4281671,752612,26.5976,0.25
ZWE,74,Zimbabwe,Harare,Africa,5202918,390757,41.7665,0.20
ARG,33,Argentina,Buenos Aires,South America,23842803,2780400,16.3683,0.57


---
### Fill missing values with `.fillna()`

- In this example, we fill all missing values with `0`
- What to fill missing values with depends on the task at hand

In [14]:
df.fillna(0) #inplace=True
df

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,NaN,33753499.0,28189672.0,NaN,10694796.0,12486631.0,10752971,652230,63.0587,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,NaN,NaN,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,NaN,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.00
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371,266000,2.1654,0.01
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607,527968,63.8232,0.42
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671,752612,26.5976,0.25
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918,390757,41.7665,0.20
ARG,33,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803,2780400,16.3683,0.57

#### Fill Forward

- `method="ffill"`

Can you spot an issue with the ASM row?

In [15]:

df.fillna(method='ffill')

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,NaN,33753499.0,28189672.0,NaN,10694796.0,12486631.0,10752971,652230,63.0587,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,2882481.0,2913399.0,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,44903225.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.00
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371,266000,2.1654,0.01
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607,527968,63.8232,0.42
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671,752612,26.5976,0.25
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918,390757,41.7665,0.20
ARG,33,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803,2780400,16.3683,0.57

#### Fill backward
fill horizontally right to left, this does not save changes to the DataFrame.

In [16]:
df.fillna(method='bfill', axis=1)

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),World Population Percentage
CCA3,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,33753499.0,33753499.0,28189672.0,10694796.0,10694796.0,12486631.0,10752971,652230,63.0587,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731,28748,98.8702,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,30774621.0,30774621.0,30774621.0,25518074.0,18739378.0,13795915,2381741,18.8531,0.56
ASM,213,American Samoa,Pago Pago,Oceania,46189.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075,199,222.4774,0.0
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860,468,170.5641,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371,266000,2.1654,0.01
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607,527968,63.8232,0.42
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,16248230.0,13792086.0,9891136.0,7686401.0,5720438.0,4281671,752612,26.5976,0.25
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918,390757,41.7665,0.2
ARG,33,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803,2780400,16.3683,0.57

---
###  Fill missing values with `.interpolate()`

Find the mid point between the values on either side.

In [17]:
df.iloc[:, 4:12].interpolate(axis=1)

,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population
CCA3,,,,,,,,
AFG,41128771.0,37441135.0,3.375350e+07,2.818967e+07,19442234.0,10694796.0,12486631.0,10752971.0
ALB,2842321.0,2866849.0,2.882481e+06,2.913399e+06,3182021.0,3295066.0,2941651.0,2324731.0
DZA,44903225.0,43451666.0,3.922598e+07,3.500030e+07,30774621.0,25518074.0,18739378.0,13795915.0
ASM,NaN,46189.0,5.136800e+04,5.484900e+04,58230.0,47818.0,32886.0,27075.0
AND,79824.0,77700.0,7.174600e+04,7.151900e+04,66097.0,53569.0,35611.0,19860.0
...,...,...,...,...,...,...,...,...
ESH,575986.0,556048.0,4.918240e+05,4.132960e+05,270375.0,178529.0,116775.0,76371.0
YEM,33696614.0,32284046.0,2.851654e+07,2.474395e+07,18628700.0,13375121.0,9204938.0,6843607.0
ZMB,20017675.0,18927715.0,1.624823e+07,1.379209e+07,9891136.0,7686401.0,5720438.0,4281671.0
ZWE,16320537.0,15669666.0,1.415494e+07,1.283977e+07,11834676.0,10113893.0,7049926.0,5202918.0
ARG,45510318.0,45036032.0,4.325706e+07,4.110012e+07,37070774.0,32637657.0,28024803.0,23842803.0

Save over the section with the interpolated version

In [18]:
df.iloc[:, 4:12] = df.iloc[:, 4:12].interpolate(axis=1)

American Samoa can't be interpolated because its NaN value sits on the end.

In [19]:
df.isna().any(axis=1)

CCA3
AFG    False
ALB    False
DZA    False
ASM     True
AND    False
       ...
ESH    False
YEM    False
ZMB    False
ZWE    False
ARG    False
Length: 235, dtype: bool

In [20]:
backfilled = df.fillna(method='bfill', axis=1)

Check that we have really dealt with the NaNs

In [21]:
backfilled.isna().any()

Rank                           False
Country                        False
Capital                        False
Continent                      False
2022 Population                False
2020 Population                False
2015 Population                False
2010 Population                False
2000 Population                False
1990 Population                False
1980 Population                False
1970 Population                False
Area (km²)                     False
Density (per km²)              False
World Population Percentage    False
dtype: bool

---
## Save clean data to a new csv.

In [22]:
backfilled.to_csv('../data/world__population_cleaned.csv')