<p style="text-align: right; font-size: small;">
Learning materials by Tamsin Huggins
</p>


# Getting started with Pandas


[Pandas User Guide](https://pandas.pydata.org/docs/user_guide/index.html#user-guide)

## Overview

- The Pandas package
- Loading in data
- Viewing the shape of the data
- Looking at data types
- Selecting columns
- Viewing unique values
- Pandas calculations on columns
- Selecting columns using conditionals

## Packages / Libraries

- A package (sometimes called a library) is essentially a set of python commands, functions and methods that you can type into your notebook to perform some work and get some results.

- You will use different python packages to perform different types of work.

- For example, producing graphs and charts requires a different package/library than performing machine learning.

- The **Pandas** package allows us to work with tables of data, very similar to using a spreadsheet such as Microsoft Excel. 

- Use the **import** statement to load this package into your notebook

## Importing the Pandas library

In [1]:
# Import Pandas
import pandas as pd

## Loading in the the data to a Pandas DataFrame
#### About the data
This dataset contains property sale prices for King County, which includes Seattle. It includes homes sold between May 2014 and May 2015.
[More](https://www.kaggle.com/harlfoxem/housesalesprediction)

In [2]:
# If the file is in your machine, you only need to give the path to the file
df = pd.read_csv("../data/kc_house_data.csv")

Call the built-in head() method on the df DataFrame, to see the first 5 rows

In [3]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

Call the built-in tail() method on the df DataFrame, to see the last 5 rows

In [4]:
df.tail()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

We can pass a number into the brackets to choose the number of rows we want to see.

In [5]:
df.head(2)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639


## Exploring the shape of the data

The use the shape attribute (.shape) to find out the number of rows and columns in your dataset.


Pandas will tell you the shape of the DataFrame in the style ( rows, columns)

In [6]:
df.shape

(21613, 21)

You can access information about the DataFrame using indexing, just like you would with a list.

Find the the number of rows.

In [7]:
df.shape[0]

21613

Find the number of columns

In [8]:
df.shape[1]

21

Have a look at the number of rows and the number of columns.

In [9]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

## Viewing the data types of the columns

In [10]:
df.dtypes

id                 int64
date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

## Selecting columns

Find out what the columns titles are by accessing the "columns" attribute of the DataFrame

In [11]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

Use square bracket indexing to access the "price" column of the DataFrame. 

Notice that in this case we can index with a text string, instead of a number. This is specific to the Pandas package.

In [12]:
df["price"]

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

Look at how the shape of the price column compares to the shape of the overall DataFrame

In [13]:
print("Dataframe shape:", (df.shape) )
print("Price column shape:", (df["price"].shape) )

Dataframe shape: (21613, 21)
Price column shape: (21613,)



Find out the datatype of the column.

In [14]:
df["price"].dtype

dtype('float64')

## Finding unique values

View the unique values in a column

In [15]:
df["bedrooms"].unique()

array([ 3,  2,  4,  5,  1,  6,  7,  0,  8,  9, 11, 10, 33], dtype=int64)

What is the number of unique values?

In [16]:
df["bedrooms"].unique().shape

(13,)

What is the count for each unique value?

In [17]:
df["bedrooms"].value_counts()

3     9824
4     6882
2     2760
5     1601
6      272
1      199
7       38
0       13
8       13
9        6
10       3
11       1
33       1
Name: bedrooms, dtype: int64

There are 2 unique values for the waterfront column. This is because 1 means that property is by the waterfront, 0 means that proerty is NOT by the waterfront. 1 oe 0 is similar to True or False

In [18]:
print(df.shape)
df["waterfront"].unique().shape

(21613, 21)

(2,)

In [19]:
df["waterfront"]

0        0
1        0
2        0
3        0
4        0
        ..
21608    0
21609    0
21610    0
21611    0
21612    0
Name: waterfront, Length: 21613, dtype: int64

In code, 1 is related to 'True' and 0 is related to 'False'

In [20]:
int(True)

1

In [21]:
int(False)

0

## Performing caluclations on columns

Find the mean average house price

In [22]:
print(df["price"].mean())

540088.1417665294

Find the median house price. What does the difference between the mean and median tell us about the house prices?

In [23]:
print(df["price"].median())

450000.0

Round the house price mean so that it has only 1 decimal place.

In [24]:
round(df["price"].mean(), 0)

540088.0

### Some useful Pandas methods to use on columns 
(I am calling them columns, but in Pandas they have the data type 'pandas.series'

<table align='left'>
<tr>
<th>Method</th>
<th>Description</th>
</tr>
<tr><td> .max() </td><td> Finds the maximum value for that column </td></tr>
<tr><td> .min() </td><td> Finds the minimim value for that column</td></tr>
<tr><td> .mean() </td><td> Finds the mean average for that column</td></tr>
    <tr><td> .median() </td><td> Finds the median for that column</td></tr>
<tr><td> .unique() </td><td> Finds the number of unique values in that column</td></tr>

### <span style="color:green"> Challenge 1: find the maximum number of bedrooms. </span>

### <span style="color:green"> Challenge 2: how old is the oldest house? </span>

## Conditionals

We often want to test if something is <span style="color:blue">True </span> or <span style="color:red"> False. </span> For this we use conditional statements or "conditionals".

There are a number of conditional operators in Python:
- **==** : Check if two elements are equal
- **!=** : NOT Equal
- **>**  : Greater than
- **>=** : Greater than OR equal to
- **<**  : Less than
- **<=** : Less than OR equal to

    >Notice the difference between "a single equals" and "double equals"
    >- A single equals makes a variable equal to something (assignment)
    >- Double equals is "asking" if two statements are the same (querying)

## Using conditionals to filter

Create a condition that says the number of bedrooms must be greater than 20.

In [25]:
condition = df["bedrooms"] > 20
condition

0        False
1        False
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Name: bedrooms, Length: 21613, dtype: bool

Use square brackets to access the part of the DataFrame in which that condition evaluates to True.

In [26]:
df[condition]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15870,2402100895,20140625T000000,640000.0,33,1.75,1620,6000,1.0,0,0,...,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700

find the price of the hosus with the most bedrooms

In [27]:
df[condition]["price"]

15870    640000.0
Name: price, dtype: float64

 ## Selecting a single value

That gives us unwanted Pandas.Series data, so call the in-built .item() method to get just the value.

In [28]:
df[condition]["price"].item()

640000.0

In [29]:
print("The price of the house with the most bedrooms is:", df[condition]["price"].item() )

The price of the house with the most bedrooms is: 640000.0

### <span style="color:green"> Challenge 3: create a new DataFrame holding only the properties that are by the waterfront. </span>
<span style="color:green"> Assign your new DataFrame to a variable (call it waterfront_houses). </span>


<span style="color:green"> Hint 1: houses by the waterfront have a value of 1 in the waterfront column, whereas houses not by the waterfront have a value of 0. </span>

<span style="color:green"> Hint 2: Start by making your condition. Look a few cells up to see how this is done </span>

### <span style="color:green"> Challenge 4: find out how much being by the waterfront affects the price of properties. </span>


<span style="color:green"> Hint: you can use the waterfront_houses dataframe you already made... </span>

## Accessing multiple columns

Accessing multiple columns. THe internal brackets mean 'this is a list', the external brackets mean indexing.

In [30]:
df[['price', 'bedrooms', 'yr_built']]

          price  bedrooms  yr_built
0      221900.0         3      1955
1      538000.0         3      1951
2      180000.0         2      1933
3      604000.0         4      1965
4      510000.0         3      1987
...         ...       ...       ...
21608  360000.0         3      2009
21609  400000.0         4      2014
21610  402101.0         2      2009
21611  400000.0         3      2004
21612  325000.0         2      2008

[21613 rows x 3 columns]

This is the same as above, broken into 2 steps.

In [31]:
columns_list = ['price', 'bedrooms', 'yr_built']
df[columns_list]

          price  bedrooms  yr_built
0      221900.0         3      1955
1      538000.0         3      1951
2      180000.0         2      1933
3      604000.0         4      1965
4      510000.0         3      1987
...         ...       ...       ...
21608  360000.0         3      2009
21609  400000.0         4      2014
21610  402101.0         2      2009
21611  400000.0         3      2004
21612  325000.0         2      2008

[21613 rows x 3 columns]

## Creating a new column based on a calculation

In [32]:
conversion_rate = 0.95

df['price_in_euros'] = df['price'] * 0.95

In [33]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price_in_euros
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,210805.00
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,511100.00
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,171000.00
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,573800.00
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,484500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,1530,0,2009,0,98103,47.6993,-122.346,1530,1509,342000.00
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,2310,0,2014,0,98146,47.5107,-122.362,1830,7200,380000.00
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,1020,0,2009,0,98144,47.5944,-122.299,1020,2007,381995.95
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,1600,0,2004,0,98027,47.5345,-122.069,1410,1287,380000.00
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,1020,0,2008,0,98144,47.5941,-122.299,1020,1357,308750.00

If we care about the position where our column is placed into the data, we can use an insert statement

df.insert(loc = location for column, column= the column name, value = value(s) for the column)

In [34]:
df.insert(loc=3, column='price_in_euros_insert', value=df['price'] * 0.95 )

In [35]:
df

,id,date,price,price_in_euros_insert,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price_in_euros
0,7129300520,20141013T000000,221900.0,210805.00,3,1.00,1180,5650,1.0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,210805.00
1,6414100192,20141209T000000,538000.0,511100.00,3,2.25,2570,7242,2.0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,511100.00
2,5631500400,20150225T000000,180000.0,171000.00,2,1.00,770,10000,1.0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,171000.00
3,2487200875,20141209T000000,604000.0,573800.00,4,3.00,1960,5000,1.0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,573800.00
4,1954400510,20150218T000000,510000.0,484500.00,3,2.00,1680,8080,1.0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,484500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,342000.00,3,2.50,1530,1131,3.0,0,...,1530,0,2009,0,98103,47.6993,-122.346,1530,1509,342000.00
21609,6600060120,20150223T000000,400000.0,380000.00,4,2.50,2310,5813,2.0,0,...,2310,0,2014,0,98146,47.5107,-122.362,1830,7200,380000.00
21610,1523300141,20140623T000000,402101.0,381995.95,2,0.75,1020,1350,2.0,0,...,1020,0,2009,0,98144,47.5944,-122.299,1020,2007,381995.95
21611,291310100,20150116T000000,400000.0,380000.00,3,2.50,1600,2388,2.0,0,...,1600,0,2004,0,98027,47.5345,-122.069,1410,1287,380000.00
21612,1523300157,20141015T000000,325000.0,308750.00,2,0.75,1020,1076,2.0,0,...,1020,0,2008,0,98144,47.5941,-122.299,1020,1357,308750.00